name: Update Publications

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update publications
        env:
          SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
        run: |
          sed -i "s/YOUR_SCHOLAR_ID/$SCHOLAR_ID/" scholar_sync.py
          python scholar_sync.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add publications.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update publications" && git push)
