name: Update Publications

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          chmod +x update_publications.sh
          ./update_publications.sh

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet publications.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add publications.md
          git commit -m "Update publications [skip ci]"
          git push
